import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css' // Import toastify CSS
import { AuthProvider } from '../context/authContext'
import './globals.css';

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased`}
      >
        <ToastContainer />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
